// ─────────────────────────────────────────────────────────
//  SERVICES.JS  —  Full service catalog with deep content
// ─────────────────────────────────────────────────────────

export const SERVICES_CATALOG = [
  {
    id: 1,
    slug: 'breakdown-repair',
    icon: 'tool',
    number: '01',
    title: 'Breakdown Repair & Service Support',
    shortDesc: 'Emergency and scheduled repair for malfunctioning CT and MRI machines. Our technician comes to your city.',
    tagline: 'Machine down? We come to you — anywhere in India.',
    colorKey: 'blue',
    badge: 'Pan India',
    badgeClass: 'badge--blue',
    category: 'repair',
    description: `When your CT or MRI machine breaks down, every hour of downtime costs your facility patients and revenue.
SEE Imaging's service team responds quickly — our experienced GE-trained technicians travel to your location to diagnose
and repair the fault on-site. Whether it's a gantry error, tube failure, detector issue, or software fault,
we carry a comprehensive inventory of spare parts so most repairs are completed in a single visit.`,
    process: [
      { step: '01', title: 'You schedule a service', desc: 'Fill the service form with machine details, the fault description, and your city.' },
      { step: '02', title: 'We call you back',       desc: 'Our technical team calls within 2–4 hours to understand the issue and plan the visit.' },
      { step: '03', title: 'Technician dispatched',  desc: 'A GE-trained technician travels to your city with the likely spare parts needed.' },
      { step: '04', title: 'On-site repair',         desc: 'Full fault diagnosis, repair, calibration, and a test scan before the technician leaves.' },
      { step: '05', title: 'Service report',         desc: 'You receive a written service report with parts replaced and work completed.' },
    ],
    covered: [
      'Gantry rotation errors and mechanical faults',
      'X-ray tube replacement and high voltage issues',
      'Detector array faults and DAS errors',
      'Software, console, and workstation issues',
      'Power supply and cooling system failures',
      'MRI RF coil and gradient amplifier faults',
      'Image quality degradation and artefacts',
      'Emergency breakdown response',
    ],
    machines: ['GE CT Scanners (all models)', 'GE MRI Systems (1.5T & 3.0T)', 'GE BrightSpeed', 'GE LightSpeed series', 'GE Discovery series'],
    urgencyOptions: ['Normal (2–5 days)', 'Urgent (24–48 hours)', 'Emergency (same day if possible)'],
    formTitle: 'Schedule a Repair Visit',
    formSubtitle: "Share your machine details and we'll dispatch a technician.",
  },
  {
    id: 2,
    slug: 'preventive-maintenance',
    icon: 'shield',
    number: '02',
    title: 'Preventive Maintenance (PM)',
    shortDesc: 'Scheduled PM visits to keep your CT or MRI system at peak performance and prevent unexpected breakdowns.',
    tagline: 'Prevention is better — and cheaper — than breakdown repair.',
    colorKey: 'teal',
    badge: 'Scheduled',
    badgeClass: 'badge--teal',
    category: 'repair',
    description: `Preventive Maintenance (PM) is a scheduled service where our technician visits your facility at agreed
intervals — 2 to 3 times per year — to inspect, clean, calibrate, and service your machine before any
fault develops. PM significantly extends equipment life, reduces sudden breakdowns, and keeps image quality
consistent. Each PM visit includes a full checklist inspection, lubrication of mechanical parts, cooling system
checks, tube warm-up protocols, and image quality verification with a phantom scan.`,
    process: [
      { step: '01', title: 'Book PM visits',          desc: 'Choose your preferred frequency — 2 visits per year (every 6 months) or 3 visits per year (every 4 months).' },
      { step: '02', title: 'Dates confirmed',          desc: 'We coordinate visit dates that minimise disruption to your patient schedule.' },
      { step: '03', title: 'Technician visit',        desc: "Full PM inspection following GE's recommended checklist for your specific machine model." },
      { step: '04', title: 'PM report delivered',     desc: 'Detailed PM report with all findings, work done, and next scheduled PM date.' },
    ],
    covered: [
      'Gantry mechanical inspection and lubrication',
      'X-ray tube warm-up and exposure check',
      'Cooling system and chiller inspection',
      'Detector calibration and noise level check',
      'Electrical safety checks and cable inspection',
      'Software patch and version verification',
      'Image quality phantom scan and sign-off',
      'Filter cleaning and internal component checks',
    ],
    machines: ['GE CT Scanners (all models)', 'GE MRI Systems (1.5T & 3.0T)'],
    urgencyOptions: ['2 visits per year (every 6 months)', '3 visits per year (every 4 months)'],
    formTitle: 'Book a PM Visit',
    formSubtitle: 'Tell us your machine and preferred visit frequency.',
  },
  {
    id: 3,
    slug: 'amc',
    icon: 'contract',
    number: '03',
    title: 'Annual Maintenance Contract (AMC)',
    shortDesc: 'Fixed annual contract — all service visits and labour covered. Spare parts billed at cost when needed.',
    tagline: 'One annual price. Unlimited service visits. Zero surprise bills.',
    colorKey: 'orange',
    badge: 'Most Popular',
    badgeClass: 'badge--orange',
    category: 'contracts',
    isContract: true,
    contractType: 'amc',
    description: `An Annual Maintenance Contract (AMC) means you pay one fixed annual fee and SEE Imaging covers all service
visits, all labour charges, and all technician travel costs for the entire year — no matter how many callouts.
AMC includes scheduled preventive maintenance visits, breakdown repair responses, and emergency callouts.
Spare parts are charged separately at cost price when a replacement is needed.
AMC gives your facility predictable maintenance costs with guaranteed response times.`,
    whatsIncluded: [
      { included: true,  item: 'Unlimited service visits throughout the year'   },
      { included: true,  item: 'All labour charges for every visit'             },
      { included: true,  item: 'Technician travel costs to your city'           },
      { included: true,  item: '2–3 preventive maintenance visits per year'       },
      { included: true,  item: 'Emergency breakdown response'                   },
      { included: true,  item: 'Software updates and calibration support'       },
      { included: true,  item: 'Service reports and maintenance documentation'  },
      { included: false, item: 'Spare parts (billed separately at cost price)'  },
      { included: false, item: 'Consumables and X-ray tube replacement'         },
    ],
    process: [
      { step: '01', title: 'Request AMC quote',     desc: 'Share your machine model, age, and city. We send a fixed annual quote.' },
      { step: '02', title: 'Contract signed',       desc: 'Review and sign the AMC agreement. Fee paid annually.' },
      { step: '03', title: 'PM visits scheduled',   desc: "We plan your 2 annual PM visits at dates that suit you." },
      { step: '04', title: 'Call us any time',      desc: 'Any breakdown during the year — one call, we come. No surprise bills.' },
    ],
    machines: ['GE CT Scanners (all models)', 'GE MRI Systems (1.5T & 3.0T)'],
    formTitle: 'Get an AMC Quote',
    formSubtitle: 'Share machine details and we\'ll send you a fixed annual price.',
  },
  {
    id: 4,
    slug: 'cmc',
    icon: 'star',
    number: '04',
    title: 'Comprehensive Maintenance Contract (CMC)',
    shortDesc: 'Full coverage — service, labour, AND spare parts all included. Full warranty on all replaced components.',
    tagline: 'Total coverage. Service, parts, and full warranty — everything included.',
    colorKey: 'purple',
    badge: 'Full Coverage',
    badgeClass: 'badge--purple',
    category: 'contracts',
    isContract: true,
    contractType: 'cmc',
    description: `A Comprehensive Maintenance Contract (CMC) is our highest level of coverage. Unlike AMC where spare
parts are billed separately, CMC covers everything — all service visits, all labour, all travel, and all spare
parts including major components. CMC also includes a full warranty on every replaced part for the contract
duration: if a replaced component fails again within the contract period, it is replaced at no additional cost.
CMC gives hospitals and diagnostic centres complete peace of mind with zero unexpected maintenance expenses.`,
    whatsIncluded: [
      { included: true, item: 'Unlimited service visits throughout the year'      },
      { included: true, item: 'All labour charges for every visit'                },
      { included: true, item: 'Technician travel costs to your city'              },
      { included: true, item: '2–3 preventive maintenance visits per year'          },
      { included: true, item: 'Emergency breakdown response'                      },
      { included: true, item: 'All spare parts included in the contract'          },
      { included: true, item: 'Full warranty on all replaced components'          },
      { included: true, item: 'Software updates and calibration support'          },
      { included: true, item: 'Priority response — faster turnaround than AMC'   },
    ],
    process: [
      { step: '01', title: 'Request CMC quote',    desc: 'Share your machine model, age, and city. We assess and prepare a full quote.' },
      { step: '02', title: 'Machine inspection',   desc: 'Our engineer may visit to assess machine condition before finalising the CMC.' },
      { step: '03', title: 'Contract signed',      desc: 'All parts, labour, and travel covered from day one of the contract.' },
      { step: '04', title: 'Full coverage active', desc: 'Any issue — parts, service, travel — all included. Zero bills for the year.' },
    ],
    machines: ['GE CT Scanners (all models)', 'GE MRI Systems (1.5T & 3.0T)'],
    formTitle: 'Get a CMC Quote',
    formSubtitle: "Tell us your machine. We'll prepare a full comprehensive coverage quote.",
  },
  {
    id: 5,
    slug: 'installation-dismantling',
    icon: 'pin',
    number: '05',
    title: 'Installation & Dismantling',
    shortDesc: 'End-to-end installation of CT and MRI systems — site prep, machine setup, calibration, and AERB guidance.',
    tagline: 'From an empty room to a scanning machine — we handle it all.',
    colorKey: 'blue',
    badge: 'Pan India',
    badgeClass: 'badge--blue',
    category: 'installation',
    description: `Installing a CT or MRI machine is a complex multi-day project requiring precise site preparation,
electrical work, RF shielding (for MRI), mechanical assembly, system calibration, and regulatory compliance.
SEE Imaging handles the complete installation process — from assessing your room to performing the acceptance
test scan. We also safely dismantle existing machines when you are upgrading or relocating equipment.`,
    process: [
      { step: '01', title: 'Site assessment',              desc: 'Our engineer visits to assess room dimensions, power supply, and floor load capacity.' },
      { step: '02', title: 'Site preparation guidance',    desc: 'We provide drawings and specs for any civil or electrical work needed beforehand.' },
      { step: '03', title: 'Machine delivery & assembly',  desc: 'Machine delivery, mechanical assembly, gantry alignment, and all cable connections.' },
      { step: '04', title: 'Calibration & test scan',      desc: 'Full system calibration, detector calibration, and acceptance test scan with phantom.' },
      { step: '05', title: 'AERB documentation',           desc: 'We assist with AERB application and compliance documentation for CT scanners.' },
    ],
    covered: [
      'Site measurement and room planning guidance',
      'Machine uncrating and mechanical assembly',
      'Electrical connections and power supply checks',
      'RF shielding assessment for MRI installations',
      'Full system calibration and acceptance test',
      'AERB compliance assistance for CT scanners',
      'Basic staff orientation on machine operation',
      'Safe dismantling of existing machines',
    ],
    machines: ['GE CT Scanners (all models)', 'GE MRI Systems (1.5T & 3.0T)'],
    urgencyOptions: ['New installation', 'Re-installation / relocation', 'Dismantling only'],
    formTitle: 'Request Installation Service',
    formSubtitle: 'Tell us your machine model and site location.',
  },
  {
    id: 6,
    slug: 'spare-parts-supply-repair',
    icon: 'parts',
    number: '06',
    title: 'Spare Parts Supply & Repair',
    shortDesc: 'Genuine and compatible GE CT Scan spare parts — fast dispatch across India. In-house repair available.',
    tagline: 'The parts you need, when you need them.',
    colorKey: 'teal',
    badge: 'In Stock',
    badgeClass: 'badge--teal',
    category: 'parts',
    description: `SEE Imaging maintains one of the largest GE CT Scan spare parts inventories in central India.
Whether you need an emergency X-ray tube or a scheduled detector module, we supply genuine and compatible
parts for all major GE CT models. Our in-house repair workshop also refurbishes faulty components —
often at 40–60% of replacement cost — with a tested and certified guarantee before dispatch.`,
    process: [
      { step: '01', title: 'Tell us the part needed', desc: 'Share your machine model and part name or the error code showing on screen.' },
      { step: '02', title: 'Quote sent',              desc: 'We confirm availability and send pricing for genuine and compatible options.' },
      { step: '03', title: 'Fast dispatch',           desc: 'Part dispatched same or next working day. Tracked courier anywhere in India.' },
      { step: '04', title: 'Technical support',       desc: 'Our engineer is available on call to guide installation of the replaced part.' },
    ],
    covered: [
      'X-ray tubes (all GE CT models)',
      'Detector array modules and DAS boards',
      'High voltage generators and inverters',
      'Slip rings and data transfer assemblies',
      'Cooling system components and chillers',
      'Gantry drive motors and position encoders',
      'Computer and workstation hardware',
      'MRI RF coils and gradient amplifiers',
    ],
    machines: ['GE HiSpeed', 'GE LightSpeed (4/8/16/32/64)', 'GE BrightSpeed', 'GE Discovery CT', 'GE Revolution EVO'],
    formTitle: 'Request a Spare Part',
    formSubtitle: 'Share the machine model and part name or error code.',
  },
  {
    id: 7,
    slug: 'technical-consultation',
    icon: 'team',
    number: '07',
    title: 'Technical Consultation',
    shortDesc: 'Expert advice on equipment purchase decisions, site planning, upgrade assessment, and AERB compliance.',
    tagline: 'Make the right decision before you spend lakhs.',
    colorKey: 'gray',
    badge: 'Free with Purchase',
    badgeClass: 'badge--gray',
    category: 'repair',
    description: `Before spending ₹20–80 lakhs on a CT or MRI machine, it pays to consult someone who has installed
and maintained hundreds of them. SEE Imaging offers technical consultation for hospitals and diagnostic centres at any
stage — from selecting the right machine for your patient volume, to planning your CT room layout, to
understanding AERB compliance requirements. Consultation is included free with any equipment purchase or service
contract, and available as a standalone service for facilities planning ahead.`,
    covered: [
      'Which machine model suits your patient volume',
      'CT room dimensions, layout, and civil requirements',
      'Electrical supply and UPS requirements',
      'AERB application and regulatory guidance',
      'Machine age and condition assessment (pre-purchase)',
      'Upgrade vs replace financial analysis',
      'AMC vs CMC — which contract suits your usage',
      'Budget planning for equipment and annual maintenance',
    ],
    machines: ['GE CT Scanners', 'GE MRI Systems', 'All radiology equipment'],
    formTitle: 'Request a Consultation',
    formSubtitle: "Tell us what you're planning. We'll help you decide.",
  },
]

export const SERVICE_CATEGORIES = [
  { value: 'all',          label: 'All Services'         },
  { value: 'repair',       label: 'Repair & Maintenance' },
  { value: 'contracts',    label: 'AMC / CMC Contracts'  },
  { value: 'installation', label: 'Installation'         },
  { value: 'parts',        label: 'Spare Parts'          },
]
